### PR TITLE
Changed the transform method for using Getters and Setters according to javabean standard.

### PR DESCRIPTION
**Pull request by tonilopezmr**
#9

So also it's compatible with other libraries.

### CODE REVIEW

**Comment by tonilopezmr** [comment]
Yes! you are right !!

**Comment by tonilopezmr** [comment]
Okey, that's all!

**Comment by txusballesteros** [comment]
Dear @tonilopezmr ,
I cannot accept your PR because that broke the previous functionality, I mean, What happens with the developers that don't use getters and setters and they are using the library? 

You have made a great job but if you don't fix the previous capabilities, I cannot accept this.

**Comment by tonilopezmr** [comment]
It's true, I've created this Pull request for the compatibility with Realm.

Anyway in the next commit I'll create support both functionalities.

**Comment by txusballesteros** [comment]
@tonilopezmr I don't like much that approach, I mean, the great way to implement this feature will be detecting if the mapped field is a method or a field.

**Comment by tonilopezmr** [comment]
@txusballesteros Good morning! Last night I finished the support in order to not break the previous functionality.

Finally it works without previous configuration. My mistake went not to think of the developers that are using the library.

**Comment by txusballesteros** [comment]
@tonilopezmr I'm here for that. :trollface:

**Comment by tonilopezmr** [comment]
@txusballesteros  lol 

Test it https://github.com/tonilopezmr/android-transformer/commit/e31a462427fa4b5b51d09d1f2843157f93d01984 and you talk to me about it.

**Comment by txusballesteros** [comment]
Hi @tonilopezmr , Can you close your PR and create an other one pointing to develop branch.

Thx

**Pull request closed without merging**
